# Dockerfile.base

FROM lambdalinux/baseimage-amzn:2017.03-004

RUN \
	yum -y update; \
    # python 3.5
    yum install -y python36-devel python36-pip; \
    pip-3.6 install boto3 nose; \
	# python 2.7
	yum install -y python27-devel python27-pip; \
	pip-2.7 install boto3 nose; \
    yum clean all;

ENV \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8
