# Dockerfile.base
# This is a base Amazon Linux image with Python2 and Python3 added with pip and boto3

FROM lambdalinux/baseimage-amzn:2017.03-004

RUN \
	yum -y update; \
    yum install -y python36-devel python36-pip; \
    pip-3.6 install boto3 pytest; \
    pip-3.6 install --upgrade pip; \
	yum install -y python27-devel python27-pip; \
	pip-2.7 install boto3 pytest; \
    pip-2.7 install --upgrade pip; \
    yum clean all;

ENV \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8
